name: ilovesales-backend Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ilovesales-backend
        environment_name: Ilovesales-backend-env-2
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        version_label: ${{ github.sha }}
        use_existing_version_if_available: false
        environment_variables: |
          IMWEB_API_KEY=${{ secrets.IMWEB_API_KEY }}
          IMWEB_SECRET_KEY=${{ secrets.IMWEB_SECRET_KEY }}
